### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cmbankester**

### CODE REVIEW

**Comment by trimstray** [comment]
This is not a mistake. Please see: [Understanding Nginx HTTP Proxying, Load Balancing, Buffering, and Caching](https://www.digitalocean.com/community/tutorials/understanding-nginx-http-proxying-load-balancing-buffering-and-caching).

**Comment by cmbankester** [comment]
Hm, maybe I’m just being dense, but that seems to suggest that the terminology used is still incorrect, as requests are proxied “to” an upstream, and responses are proxied “from” an upstream. However, this is a fairly insignificant detail, and there’s really nothing seriously wrong here, so I have no reason to press the matter

**Comment by trimstray** [comment]
No it's important, you're right. I didn't understand what you mean and didn't focus on this. I'm so sorry.

**Comment by trimstray** [comment]
@cmbankester : thx for this :+1:

**Comment by cmbankester** [comment]
Of course! Glad to help

**Pull request merged**
